["run_parameters"]
task = "regression"
debug = false
n_splits = [10]
test_size = 0.2
split_kind = "group_shuffle"


["join_parameters"]
join_strategy = "left"
aggregation = ["first"]

["evaluation_models"]
chosen_model = ["linear", "catboost"]
catboost.iterations = 300
catboost.od_type = "Iter"
catboost.od_wait = 10
catboost.l2_leaf_reg = 0.01
catboost.thread_count = 32


["estimators"]
no_join.active = true
stepwise_greedy_join.active = true
highest_containment.active = true
best_single_join.active = true
full_join.active = true
stepwise_greedy_join.budget_type = "iterations"
stepwise_greedy_join.budget_amount = [30]
stepwise_greedy_join.epsilon = [0.0]
stepwise_greedy_join.ranking_metric = "containment"

["query_cases"]
data_lake = ["wordnet_full"]
join_discovery_method = ["exact_matching", "minhash", "minhash_hybrid"]
table_path = [
    "data/source_tables/yadl/us_elections-yadl-depleted.parquet",
    "data/source_tables/yadl/us_elections-old-yadl-depleted.parquet",
    "data/source_tables/yadl/us_elections-dems-yadl-depleted.parquet",
    "data/source_tables/yadl/us_elections-old-yadl-depleted.parquet",
    # "data/source_tables/yadl/us_elections-yadl.parquet",
]
query_column = "col_to_embed"
top_k = [30]
