# environment.yaml
name: bench
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - polars==0.20.5
  - pandas==1.5.3
  - numpy==1.24.3
  - woodwork==0.24.0
  - scikit-learn==1.2.2
  - scipy==1.12.0
  - matplotlib==3.7.1
  - seaborn==0.12.2
  - gitpython==3.1.31
  - catboost==1.2
  - tqdm==4.65.0
  - jupyter
  - featuretools==1.26.0
  - pyarrow==12.0
  - pre-commit==3.4.0
  - toml
