# environment.yaml
name: bench-repro
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
    - -r file:requirements.txt
  - polars==0.18.4
  - pandas==1.5.3
  - numpy==1.24.3
  - woodwork==0.24.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - matplotlib==3.7.1
  - seaborn==0.12.2
  - gitpython==3.1.31
  - catboost==1.2
  - datasketch==1.5.9
  - tqdm==4.65.0
  - jupyter
  - featuretools==1.26.0
