[["minhash"]]
metadata_dir="data/metadata/binary_update"
num_perm=128
thresholds=[20]
n_jobs=1
no_tag=false

[["minhash"]]
metadata_dir="data/metadata/binary_update"
num_perm=128
thresholds=[40]
n_jobs=1
no_tag=false

[["minhash"]]
metadata_dir="data/metadata/binary_update"
num_perm=128
thresholds=[80]
n_jobs=1
no_tag=false
