# Movies large
[["exact_matching"]]
n_jobs=16
metadata_dir="data/metadata/open_data_us"
base_table_path="data/source_tables/open_data_us/movies_large-depleted-open_data.parquet"
query_column="original_title"

# Movies vote large
[["exact_matching"]]
n_jobs=16
metadata_dir="data/metadata/open_data_us"
base_table_path="data/source_tables/open_data_us/movies_vote_large-depleted-open_data.parquet"
query_column="original_title"

# US Accidents 2021
[["exact_matching"]]
n_jobs=16
metadata_dir="data/metadata/open_data_us"
base_table_path="data/source_tables/open_data_us/us_accidents_2021-depleted-open_data_County.parquet"
query_column="County"

# US accidents large
[["exact_matching"]]
n_jobs=16
metadata_dir="data/metadata/open_data_us"
base_table_path="data/source_tables/open_data_us/us_accidents_large-depleted-open_data_County.parquet"
query_column="County"
