# Wordnet_big
[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/us-elections-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/housing-prices-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/company-employees-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/movies-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/movies-vote-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/batch/us-accidents-yadl-depleted.parquet"
query_column="col_to_embed"

# Binary
[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/us-elections-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/housing-prices-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/company-employees-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/movies-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/movies-vote-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/batch/us-accidents-yadl-depleted.parquet"
query_column="col_to_embed"
