[["count_vectorizer"]]
data_lake_path="wordnet_big"
base_table_path="data/source_tables/company-employees-yadl.parquet"
query_column="col_to_embed"

[["count_vectorizer"]]
data_lake_path="open_data_us"
base_table_path="data/source_tables/company-employees-yadl.parquet"
query_column="name"

[["count_vectorizer"]]
data_lake_path="wordnet_big"
base_table_path="data/source_tables/movies-yadl.parquet"
query_column="col_to_embed"

[["count_vectorizer"]]
data_lake_path="open_data_us"
base_table_path="data/source_tables/movies-yadl.parquet"
query_column="title"

[["count_vectorizer"]]
data_lake_path="wordnet_big"
base_table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="col_to_embed"

[["count_vectorizer"]]
data_lake_path="open_data_us"
base_table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="county"
