# [["exact_matching"]]
# metadata_dir="data/metadata/binary_update"
# base_table_path="data/source_tables/company-employees-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/binary_update"
# base_table_path="data/source_tables/movies-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/binary_update"
# base_table_path="data/source_tables/us-accidents-yadl.parquet"
# query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/new_datasets/us_elections-yadl.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/new_datasets/housing_prices-yadl.parquet"
query_column="col_to_embed"
