# wordnet_full_flat
# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/us-elections-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/housing-prices-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/company-employees-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/movies-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/movies-vote-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/batch/us-accidents-yadl.parquet"
# query_column="col_to_embed"

# [["exact_matching"]]
# metadata_dir="data/metadata/wordnet_full_flat"
# base_table_path="data/source_tables/yadl/us_county_population-depleted-yadl.parquet"
# query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/binary_update"
base_table_path="data/source_tables/yadl/us_county_population-depleted-yadl.parquet"
query_column="col_to_embed"
