[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/us-elections-yadl.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/housing-prices-yadl.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/company-employees-yadl.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/movies-yadl.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_big"
base_table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="col_to_embed"
