[["minhash"]]
data_dir="data/metadata/wordnet_big"
thresholds=[10]
oneshot=true
num_perm=128
n_jobs=-1

[["minhash"]]
data_dir="data/metadata/wordnet_big"
thresholds=[20]
oneshot=true
num_perm=128
n_jobs=-1

# [["minhash"]]
# data_dir="data/metadata/wordnet_big"
# thresholds=[30]
# oneshot=true
# num_perm=128
# n_jobs=-1

[["minhash"]]
data_dir="data/metadata/wordnet_big"
thresholds=[40]
oneshot=true
num_perm=128
n_jobs=-1

# [["minhash"]]
# data_dir="data/metadata/wordnet_big"
# thresholds=[50]
# oneshot=true
# num_perm=128
# n_jobs=-1

[["minhash"]]
data_dir="data/metadata/wordnet_big"
thresholds=[60]
oneshot=true
num_perm=128
n_jobs=-1

[["minhash"]]
data_dir="data/metadata/wordnet_big"
thresholds=[80]
oneshot=true
num_perm=128
n_jobs=-1
