join_discovery_method=["exact_matching", "minhash"]
data_lake="wordnet_full_flat"

[["query_cases"]]
table_path="data/source_tables/batch/us-elections-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/batch/housing-prices-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/batch/company-employees-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/batch/movies-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/batch/us-accidents-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/batch/movies-vote-yadl-depleted.parquet"
query_column="col_to_embed"
