["run_parameters"]
task="regression"
debug=false
n_splits=15
test_size=0.2
split_kind="group_shuffle"
top_k=50

[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/company-employees-yadl.parquet"
query_column="name"
[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/movies-yadl.parquet"
query_column="title"
[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="County"
[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="Zipcode"
[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/us-presidential-results-yadl.parquet"
query_column="county_name"

# METAM
[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/housing-open_data.parquet"
query_column="CITY"

[["query_cases"]]
join_discovery_method="minhash"
data_lake="open_data_us"
table_path="data/source_tables/housing-open_data.parquet"
query_column="ZIP"



["join_parameters"]
join_strategy="left"
aggregation=["first"]

["evaluation_models"]
chosen_model=["linear","catboost"]
catboost.iterations=500
catboost.od_type="Iter"
catboost.od_wait=10
catboost.l2_leaf_reg=0.01

["estimators"]
no_join.active=true
stepwise_greedy_join.active=true
highest_containment.active=true
best_single_join.active=true
full_join.active=true
stepwise_greedy_join.budget_type="iterations"
stepwise_greedy_join.budget_amount=[20]
stepwise_greedy_join.epsilon=[0.0]
stepwise_greedy_join.ranking_metric="containment"
