["run_parameters"]
task="regression"
debug=true
n_splits=[2]
test_size=0.2
split_kind="group_shuffle"
top_k=30


# [["query_cases"]]
# data_lake="wordnet_big"
# join_discovery_method="minhash"
# table_path="data/source_tables/new_datasets/us_elections-yadl.parquet"
# query_column="col_to_embed"

[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/new_datasets/housing_prices-yadl.parquet"
query_column="col_to_embed"


["join_parameters"]
join_strategy="left"
aggregation=["first"]

["evaluation_models"]
chosen_model=["catboost"]
catboost.iterations=10
catboost.od_type="Iter"
catboost.od_wait=10
catboost.l2_leaf_reg=0.01

["estimators"]
no_join.active=true
stepwise_greedy_join.active=true
highest_containment.active=true
best_single_join.active=true
full_join.active=true
stepwise_greedy_join.budget_type="iterations"
stepwise_greedy_join.budget_amount=[20]
stepwise_greedy_join.epsilon=[0.0]
stepwise_greedy_join.ranking_metric="containment"
