["run_parameters"]
task="regression"
debug=false
n_splits=[10]
test_size=0.2
split_kind="group_shuffle"
variable_of_interest="jd_method"

["join_parameters"]
join_strategy="left"
aggregation=["first"]

["evaluation_models"]
chosen_model=["linear", "catboost"]
catboost.iterations=300
catboost.od_type="Iter"
catboost.od_wait=10
catboost.l2_leaf_reg=0.01

["estimators"]
no_join.active=true
stepwise_greedy_join.active=true
highest_containment.active=true
best_single_join.active=true
full_join.active=true
stepwise_greedy_join.budget_type="iterations"
stepwise_greedy_join.budget_amount=[20]
stepwise_greedy_join.epsilon=[0.0]
stepwise_greedy_join.ranking_metric="containment"

# US Elections
[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/us-elections-yadl.parquet"
query_column="col_to_embed"
top_k=30


[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="exact_matching"
table_path="data/source_tables/us-elections-yadl.parquet"
query_column="col_to_embed"
top_k=30

# Housing prices
[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/housing-prices-yadl.parquet"
query_column="col_to_embed"
top_k=30

[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="exact_matching"
table_path="data/source_tables/housing-prices-yadl.parquet"
query_column="col_to_embed"
top_k=30

# Company employees
[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/company-employees-yadl.parquet"
query_column="col_to_embed"
top_k=30

[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="exact_matching"
table_path="data/source_tables/company-employees-yadl.parquet"
query_column="col_to_embed"
top_k=30

# Movies
[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/movies-yadl.parquet"
query_column="col_to_embed"
top_k=30

[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="exact_matching"
table_path="data/source_tables/movies-yadl.parquet"
query_column="col_to_embed"
top_k=30

# US accidents
[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="minhash"
table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="col_to_embed"
top_k=30

[["query_cases"]]
data_lake="wordnet_big"
join_discovery_method="exact_matching"
table_path="data/source_tables/us-accidents-yadl.parquet"
query_column="col_to_embed"
top_k=30
