["run_parameters"]
source_table_path=["data/source_tables/schools-depleted-open_data.parquet"]
debug=false
n_splits=[5, 10]
target_column="target"
test_size=0.2
split_kind="group_shuffle"
query_column="col_to_embed"

["jd_parameters"]
selected_indices = "minhash"
top_k=30
data_lake = "open_data_large"

["join_parameters"]
join_strategy="left"
aggregation=["first"]

["evaluation_models"]
linear.active=[false, true]
catboost.active=true
catboost.iterations=500
catboost.od_type="Iter"
catboost.od_wait=10
catboost.l2_leaf_reg=0.01

["estimators"]
no_join.active=false
highest_containment.active=false
best_single_join.active=false
full_join.active=false
stepwise_greedy_join.active=false
stepwise_greedy_join.budget_type="iterations"
stepwise_greedy_join.budget_amount=[20, 50]
stepwise_greedy_join.epsilon=[0.0]
stepwise_greedy_join.ranking_metric="containment"
stepwise_greedy_join.metric="r2"
