# wordnet_full
[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/us-elections-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/housing-prices-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/company-employees-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/movies-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/movies-vote-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/batch/us-accidents-yadl-depleted.parquet"
query_column="col_to_embed"

[["exact_matching"]]
metadata_dir="data/metadata/wordnet_full"
base_table_path="data/source_tables/yadl/us_county_population-depleted-yadl.parquet"
query_column="col_to_embed"
