join_discovery_method=["exact_matching", "minhash"]
data_lake="wordnet_full_flat"

# [["query_cases"]]
# table_path="data/source_tables/batch/us-elections-yadl.parquet"
# query_column="col_to_embed"

# [["query_cases"]]
# table_path="data/source_tables/batch/housing-prices-yadl.parquet"
# query_column="col_to_embed"

# [["query_cases"]]
# table_path="data/source_tables/batch/company-employees-yadl.parquet"
# query_column="col_to_embed"

# [["query_cases"]]
# table_path="data/source_tables/batch/movies-yadl.parquet"
# query_column="col_to_embed"

# [["query_cases"]]
# table_path="data/source_tables/batch/us-accidents-yadl.parquet"
# query_column="col_to_embed"

# [["query_cases"]]
# table_path="data/source_tables/batch/movies-vote-yadl.parquet"
# query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/us_county_population-depleted-yadl.parquet"
query_column="col_to_embed"
