join_discovery_method=["exact_matching"]
data_lake="wordnet_full"
hybrid=true

[["query_cases"]]
table_path="data/source_tables/yadl/us_elections-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/housing_prices-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/company_employees-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/movies-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/us_accidents-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/movies_vote-yadl.parquet"
query_column="col_to_embed"
