join_discovery_method=["starmie"]
data_lake="binary_update"
iterations=1

[["query_cases"]]
table_path="data/source_tables/yadl/us_elections-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/housing_prices-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/company_employees-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/movies_large-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/us_accidents_2021-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/us_accidents_large-yadl-depleted.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/yadl/us_county_population-yadl-depleted.parquet"
query_column="col_to_embed"
