join_discovery_method=["exact_matching"]
data_lake="open_data_us"

# Company employees
[["query_cases"]]
table_path="data/source_tables/open_data_us/company_employees-open_data.parquet"
query_column="name"

[["query_cases"]]
table_path="data/source_tables/open_data_us/company_employees-depleted_name-open_data.parquet"
query_column="name"

# Housing prices
[["query_cases"]]
table_path="data/source_tables/open_data_us/housing_prices-open_data.parquet"
query_column="County"

[["query_cases"]]
table_path="data/source_tables/open_data_us/housing_prices-depleted_County-open_data.parquet"
query_column="County"

# US elections
[["query_cases"]]
table_path="data/source_tables/open_data_us/us_elections-open_data.parquet"
query_column="county_name"

[["query_cases"]]
table_path="data/source_tables/open_data_us/us_elections-depleted_county_name-open_data.parquet"
query_column="county_name"

# Movies
[["query_cases"]]
table_path="data/source_tables/open_data_us/movies-depleted_title-open_data.parquet"
query_column="title"

[["query_cases"]]
table_path="data/source_tables/open_data_us/movies-open_data.parquet"
query_column="title"


# Movies vote
[["query_cases"]]
table_path="data/source_tables/open_data_us/movies_vote-open_data.parquet"
query_column="title"

[["query_cases"]]
table_path="data/source_tables/open_data_us/movies_vote-depleted_title-open_data.parquet"
query_column="title"

# US Accidents

[["query_cases"]]
table_path="data/source_tables/open_data_us/us_accidents-open_data.parquet"
query_column="County"

[["query_cases"]]
table_path="data/source_tables/open_data_us/us_accidents-depleted_County-open_data.parquet"
query_column="County"
