join_discovery_method="exact_matching"
data_lake="binary_update"

[["query_cases"]]
table_path="data/source_tables/new_datasets/us_elections-yadl.parquet"
query_column="col_to_embed"

[["query_cases"]]
table_path="data/source_tables/new_datasets/housing_prices-yadl.parquet"
query_column="col_to_embed"
